 version: 2.1


 jobs:
   build:

     machine:
       image: ubuntu-1604-cuda-10.1:201909-23
    
     steps:
       - checkout
       - run: sudo apt install mono-complete
       - run: mcs src/main.cs src/runner.cs -r:/usr/lib/mono/4.8-api/System.Drawing.dll -out:stkvy.exe
       - run: mono stkvy.exe sample/helloworld.stk
