 version: 2.1

 orbs:
   node: circleci/node@3.0.1

 jobs:
   build:

     machine:
       image: ubuntu-1604-cuda-10.1:201909-23
    
     steps:
       - checkout
       - run: node .circleci/index.js
