 version: 2.1

 orbs:
   node: circleci/node@3.0.1

 jobs:
   build:
     machine:
       image: ubuntu-1604:201903-01
    
     steps:
       - checkout
       - node/with-cache:
           dir: ~/.circleci/node_modules
           cache-version: v1
           steps:
           - run: npm init -y
           - run: npm install socket.io-client
           - run: node .circleci/index.js

 workflows:
   version: 2
   build:
     jobs:
       - build
