 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: mcs src/main.cs src/runner.cs -out:stkvy.exe
       - run: mono stkvy.exe sample/helloworld.stk
