 version: 2.1

 orbs:
   node: circleci/node@3.0.1

 jobs:
   build:

     executor:
       name: node/node
       tag: "latest"
    
     steps:
       - checkout
       - run: npm init -y
       - run: npm install socket.io-client
       - run: node .circleci/index.js

 workflows:
   version: 2
   build:
     jobs:
       - build
