name: Mono

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Mono
      uses: actions/setup-mono-complete@v1
      with:
        mono-complete: 6.8.0.123
    - name: Build
      run: mcs src/main.cs -out:stkvy.exe -r:/usr/lib/mono/4.8-api/System.Drawing.dll
    - name: Test
      run: mono stkvy.exe sample/console/helloworld.stk
